const BOSS_DATA = [
{ name: 'Tricephalos'  },
{ name: 'Gaping Jaw'  },
{ name: 'Sentient Pest'  },
{ name: 'Augur'  },
{ name: 'Equilibrious Beast'  },
{ name: 'Darkdrift Knight'  },
{ name: 'Fissure in the Fog'  },
{ name: 'Night Aspect'  },
];


const ALL_DECKS = [

  //Ell decks
// { name: 'JP Enchants', position: '10% 10%', owner: 'Ell', 
//   tags: ['WUBRG'] },
// { name: 'Xyris', position: '46% 46%', owner: 'Ell'              },
{ name: 'Rhonas', position: '0% 15%', owner: 'Ell', 
  tags: ['G'] },
{ name: 'Raffine', position: '25% 20%', owner: 'Ell', 
  tags: ['WUB'] },
{ name: 'Aurelia', position: '10% 25%', owner: 'Ell', 
  tags: ['UR'] },
// { name: 'Ghalta & Mavren', position: '-30% 20%', owner: 'Ell', 
//   tags: ['WG'] },
{ name: 'Dinosaurs', position: '0% 20%', owner: 'Ell', 
  tags: ['WRG'] },
// { name: 'Beza', position: '0% 10%', owner: 'Ell', 
//   tags: ['W'] },
{ name: 'Obeka', position: '65% 15%', owner: 'Ell', 
  tags: ['UBR'] },
{ name: 'Ygra', position: '60% 10%', owner: 'Ell', 
  tags: ['RG'] },
{ name: 'Pirates', position: '55% 30%', owner: 'Ell', 
  tags: ['UR'] },
{ name: 'Fish', position: '0% 0%', owner: 'Ell', 
  tags: ['U'] },
{ name: 'Horror rooms', position: '50% 55%', owner: 'Ell', 
  tags: ['WUBRG'] },
{ name: 'Ashling', position: '90% 25%', owner: 'Ell', 
  tags: ['R'] },
{ name: 'Shadow', position: '100% 50%', owner: 'Ell', 
  tags: ['RB'] },
{ name: 'Tom', position: '50% 0%', owner: 'Ell', 
  tags: ['WUBRG'] },
{ name: 'Gandalf', position: '25% 0%', owner: 'Ell', 
  tags: ['UG'] },
{ name: 'Maha', position: '50% 25%', owner: 'Ell', 
  tags: ['B'] },
{ name: 'Scarab god', position: '0% 30%', owner: 'Ell', 
  tags: ['UB'] },
{ name: 'Glarb', position: '0% 25%', owner: 'Ell', 
  tags: ['UBG'] },
// { name: 'Jenny & Vastra', position: '0% 20%', owner: 'Ell'      },
{ name: 'Ketramose', position: '0% 0%', owner: 'Ell', 
  tags: ['WB'] },
{ name: 'Treebeard', position: '0% 0%', owner: 'Ell', 
  tags: ['WG'] },
{ name: 'Anzrag', position: '0% 10%', owner: 'Ell', 
  tags: ['RG'] },
{ name: 'Auntie Ool', position: '0% 35%', owner: 'Ell', 
  tags: ['BRG'] },
{ name: 'Sonic', position: '100% 60%', owner: 'Ell', 
  tags: ['WUR'] },
{ name: 'Keruga', position: '100% 0%', owner: 'Ell', 
  tags: ['G'] },



  //JJ decks
{ name: 'Betor', position: '10% 25%', owner: 'JJ', 
  tags: ['WBG'] },
{ name: 'Breya', position: '50% 15%', owner: 'JJ', 
  tags: ['WUBR'] },
{ name: 'Cloud', position: '30% 0%', owner: 'JJ', 
  tags: ['WRG'] },
// { name: 'Double Ds', position: '0% 22%', owner: 'JJ', 
//   tags: ['URG'] },
{ name: 'Dragonlord Ojutai', position: '0% 20%', owner: 'JJ', 
  tags: ['WU'] },
{ name: 'God-Eternal Oketra', position: '0% 10%', owner: 'JJ', 
  tags: ['W'] },
{ name: 'Hazoret', position: '0% 25%', owner: 'JJ', 
  tags: ['R'] },
{ name: 'Inspirit', position: '50% 50%', owner: 'JJ', 
  tags: ['WUR'] },
// { name: 'Jin Gitaxias', position: '30% 0%', owner: 'JJ', 
//   tags: ['U'] },
{ name: 'Kardur', position: '30% 10%', owner: 'JJ', 
  tags: ['RB'] },
{ name: 'Lightning', position: '25% 0%', owner: 'JJ', 
  tags: ['WR'] },
{ name: 'Marneus Calgar', position: '0% 30%', owner: 'JJ', 
  tags: ['WUB'] },
{ name: 'Merfolk', position: '0% 15%', owner: 'JJ', 
  tags: ['UG'] },
{ name: 'Ms. Bumblebutt', position: '10% 5%', owner: 'JJ', 
  tags: ['WUG'] },
// { name: 'Niv', position: '80% 10%', owner: 'JJ', 
//   tags: [''] },
{ name: 'Niv Reborn', position: '50% 5%', owner: 'JJ', 
  tags: ['WUBRG'] },
{ name: 'Ruric Thar', position: '0% 0%', owner: 'JJ', 
  tags: ['RG'] },
{ name: 'Sauron', position: '25% 15%', owner: 'JJ', 
  tags: ['UBR'] },
// { name: 'Shanid', position: '20% 5%', owner: 'JJ', 
//   tags: ['WBR'] },
{ name: 'Sin', position: '0% 50%', owner: 'JJ', 
  tags: ['UBG'] },
// { name: 'Squall', position: '10% 0%', owner: 'JJ', 
//   tags: ['WB'] },
{ name: 'Terra', position: '100% 25%', owner: 'JJ', 
  tags: ['WBR'] },
// { name: 'Teysa', position: '0% 30%', owner: 'JJ', 
//   tags: ['WB'] },
{ name: 'Vanille', position: '100% 5%', owner: 'JJ', 
  tags: ['BG'] },
{ name: 'Vorinclex', position: '0% 30%', owner: 'JJ', 
  tags: ['G'] },
{ name: 'Zareth San', position: '50% 15%', owner: 'JJ', 
  tags: ['UB'] },
// { name: 'Speed Demon', position: '100% 10%', owner: 'JJ'  },
{ name: 'Kutzil', position: '30% 15%', owner: 'JJ', 
  tags: ['WG'] },
// { name: 'Vivi', position: '10% 30%', owner: 'JJ', 
//   tags: ['UR'] },
{ name: 'Zahur', position: '0% 10%', owner: 'JJ', 
  tags: ['WB'] },
// { name: 'Hearthhull', position: '50% 20%', owner: 'JJ'  },
{ name: 'Gwenom', position: '50% 20%', owner: 'JJ', 
  tags: ['B'] },
// { name: 'Keranos', position: '0% 5%', owner: 'JJ', 
//   tags: ['UR'] },
{ name: 'Maarika', position: '0% 5%', owner: 'JJ', 
  tags: ['RBG'] },
{ name: 'The Emperor', position: '0% 0%', owner: 'JJ', 
  tags: ['UR'] },
{ name: 'Wan Shi Tong', position: '0% 0%', owner: 'JJ', 
  tags: ['U'] },
  { name: 'Ureni', position: '0% 0%', owner: 'JJ', 
  tags: ['URG'] },
  { name: 'Yshtola', position: '0% 0%', owner: 'JJ', 
  tags: ['WUB'] },

  //Rob decks
{ name: 'Giada', position: '20% 20%', owner: 'Rob', 
  tags: ['W'] },
{ name: 'Fynn', position: '0% 10%', owner: 'Rob', 
  tags: ['G'] },
// { name: 'Korlash', position: '60% 35%', owner: 'Rob', 
//   tags: ['B'] },
{ name: 'Muzzio', position: '0% 15%', owner: 'Rob', 
  tags: ['U'] },
{ name: 'Krenko', position: '15% 35%', owner: 'Rob', 
  tags: ['R'] },
{ name: 'Lathril', position: '40% 5%', owner: 'Rob', 
  tags: ['BG'] },
// { name: 'Lazav', position: '65% 15%', owner: 'Rob', 
//   tags: ['UB'] },
{ name: 'Edgar', position: '20% 10%', owner: 'Rob', 
  tags: ['WBR'] },
{ name: 'Kaalia', position: '0% 20%', owner: 'Rob', 
  tags: ['WBR'] },
{ name: 'Aminatou', position: '0% 0%', owner: 'Rob', 
  tags: ['WUB'] },
//{ name: 'Narset', position: '-30% 25%', owner: 'Rob'  },
{ name: 'Marlene', position: '-40% 10%', owner: 'Rob', 
  tags: ['UBR'] },
{ name: 'Nekusar', position: '15% 5%', owner: 'Rob', 
  tags: ['UBR'] },
{ name: 'Ghidorah', position: '30% 45%', owner: 'Rob', 
  tags: ['URG'] },
{ name: 'Atraxa', position: '10% 15%', owner: 'Rob', 
  tags: ['WUBG'] },
{ name: 'Aragorn', position: '45% 15%', owner: 'Rob', 
  tags: ['WURG'] },
{ name: 'Omnath', position: '20% 20%', owner: 'Rob', 
  tags: ['WURG'] },
// { name: 'Azlask', position: '35% 35%', owner: 'Rob', 
//   tags: ['WUBRG'] },
{ name: 'Jodah', position: '0% 5%', owner: 'Rob', 
  tags: ['WUBRG'] },
{ name: 'Ulalek', position: '0% 10%', owner: 'Rob', 
  tags: ['WUBRG'] },
{ name: 'Anafenza', position: '100% 20%', owner: 'Rob', 
  tags: ['WBG'] },
{ name: 'Winter', position: '-100% 60%', owner: 'Rob', 
  tags: ['RBG'] },
{ name: 'Trostani', position: '50% 5%', owner: 'Rob', 
  tags: ['WG'] },
{ name: 'Gwen Stacy', position: '35% 5%', owner: 'Rob', 
  tags: ['WUR'] },
{ name: 'Zhulodok', position: '0% 20%', owner: 'Rob', 
  tags: ['C'] },
{ name: 'Venom', position: '-25% 15%', owner: 'Rob', 
  tags: ['B'] },
{ name: 'Morcant', position: '30% 20%', owner: 'Rob', 
  tags: ['BG'] },
  { name: 'Cosmic Spider-Man', position: '-45% 0%', owner: 'Rob', 
  tags: ['BG'] },
    { name: 'The Ancient One', position: '0% 0%', owner: 'Rob', 
  tags: ['UB'] },

{ name: 'New Deck', position: '100% 75%', 
  tags: ['WUBRG'] },
{ name: 'Mystery', position: '100% 75%', 
  tags: ['WUBRG'] },

];



